/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/repository/EntityRepository.e.vm.java
 */
package com.jaxio.demo.jpa.repository;

import org.springframework.data.jpa.repository.*;

import com.jaxio.demo.jpa.model.AppAuthority;

/**
 * AppAuthority repository.
 * 
 * @author generated by Celerio
 *
 */
public interface AppAuthorityJpaRepository extends JpaRepository<AppAuthority, Integer> {

}