/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/repository/EntityRepository.e.vm.java
 */
package com.jaxio.demo.repository;

import org.springframework.data.jpa.repository.*;

import com.jaxio.demo.domain.AppToken;

/**
 * AppToken repository.
 * 
 * @author generated by Celerio
 *
 */
public interface AppTokenRepository extends JpaRepository<AppToken, String> {

}