# codecov key : 69b49f55-e2d8-4198-9171-d039c688d8c8
language: java
sudo: false # faster builds
addons:
  sonarcloud:
    organization: "ave-cesar-github"
    token:
      secure: "fd58d58af0497452b3feec549eaf67a6a16ced18"
jdk:
  - oraclejdk8
script: 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent -Pdb,metadata,gen compile sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash) 
  