language: java
sudo: false # faster builds
addons:
  sonarcloud:
    organization: "ave-cesar-github"
    token:
      secure: "fd58d58af0497452b3feec549eaf67a6a16ced18"
jdk:
  - oraclejdk8
script: 
  - mvn -Pdb,metadata,gen
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent -Pdb,metadata,gen compile cobertura:cobertura sonar:sonar

  