/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/config/LoggingAspectConfiguration.p.vm.java
 */
package com.jaxio.demo.config;

import org.springframework.context.annotation.*;

import com.jaxio.demo.aop.LoggingAspect;

/**
 * Configures logging through AOP.
 *
 */
@Configuration
@EnableAspectJAutoProxy
public class LoggingAspectConfiguration {

    @Bean
    @Profile("dev")
    public LoggingAspect loggingAspect() {
        return new LoggingAspect();
    }
}