/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/utils/EntityUtils.e.vm.java
 */
package com.jaxio.demo.utils;

import java.math.BigDecimal;

import com.jaxio.demo.jpa.model.AppParameter;

public class AppParameterEntityUtils {

    public static AppParameter createNewAppParameter(String id) {
        AppParameter appParameter = new AppParameter();
        // FIXME à terminer		
        /*		
        		appParameter.setId("Toto");
        		appParameter.setDomain("Toto");
        		appParameter.setKey("Toto");
        		appParameter.setValue("Toto");
        */
        return appParameter;
    }

    public static com.jaxio.demo.elasticsearch.model.AppParameter createNewElasticsearchAppParameter(String id) {
        com.jaxio.demo.elasticsearch.model.AppParameter appParameter = new com.jaxio.demo.elasticsearch.model.AppParameter();

        return appParameter;
    }

    public static com.jaxio.demo.elasticsearch.model.AppParameter convertToElasticsearchAppParameter(AppParameter appParameter) {
        com.jaxio.demo.elasticsearch.model.AppParameter elasticsearchAppParameter = new com.jaxio.demo.elasticsearch.model.AppParameter();

        elasticsearchAppParameter.setId(appParameter.getId());
        elasticsearchAppParameter.setDomain(appParameter.getDomain());
        elasticsearchAppParameter.setKey(appParameter.getKey());
        elasticsearchAppParameter.setValue(appParameter.getValue());

        return elasticsearchAppParameter;
    }
}
