/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/utils/EntityUtils.e.vm.java
 */
package com.jaxio.demo.utils;

import java.math.BigDecimal;

import com.jaxio.demo.jpa.model.AppToken;

public class AppTokenEntityUtils {

    public static AppToken createNewAppToken(String id) {
        AppToken appToken = new AppToken();
        // FIXME à terminer		
        /*		
        		appToken.setId("Toto");
        		appToken.setTokenValue("Toto");
        		appToken.setTokenCreationDate("Toto");
        		appToken.setIpAddress("Toto");
        		appToken.setUserAgent("Toto");
        		appToken.setUserLogin("Toto");
        */
        return appToken;
    }

    public static com.jaxio.demo.elasticsearch.model.AppToken createNewElasticsearchAppToken(String id) {
        com.jaxio.demo.elasticsearch.model.AppToken appToken = new com.jaxio.demo.elasticsearch.model.AppToken();

        return appToken;
    }

    public static com.jaxio.demo.elasticsearch.model.AppToken convertToElasticsearchAppToken(AppToken appToken) {
        com.jaxio.demo.elasticsearch.model.AppToken elasticsearchAppToken = new com.jaxio.demo.elasticsearch.model.AppToken();

        elasticsearchAppToken.setId(appToken.getId());
        elasticsearchAppToken.setTokenValue(appToken.getTokenValue());
        elasticsearchAppToken.setTokenCreationDate(appToken.getTokenCreationDate());
        elasticsearchAppToken.setIpAddress(appToken.getIpAddress());
        elasticsearchAppToken.setUserAgent(appToken.getUserAgent());
        elasticsearchAppToken.setUserLogin(appToken.getUserLogin());

        return elasticsearchAppToken;
    }
}
