/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/utils/EntityUtils.e.vm.java
 */
package com.jaxio.demo.utils;

import java.math.BigDecimal;

import com.jaxio.demo.jpa.model.AppTranslation;

public class AppTranslationEntityUtils {

    public static AppTranslation createNewAppTranslation(String id) {
        AppTranslation appTranslation = new AppTranslation();
        // FIXME à terminer		
        /*		
        		appTranslation.setId("Toto");
        		appTranslation.setLanguage("Toto");
        		appTranslation.setKey("Toto");
        		appTranslation.setValue("Toto");
        */
        return appTranslation;
    }

    public static com.jaxio.demo.elasticsearch.model.AppTranslation createNewElasticsearchAppTranslation(String id) {
        com.jaxio.demo.elasticsearch.model.AppTranslation appTranslation = new com.jaxio.demo.elasticsearch.model.AppTranslation();

        return appTranslation;
    }

    public static com.jaxio.demo.elasticsearch.model.AppTranslation convertToElasticsearchAppTranslation(AppTranslation appTranslation) {
        com.jaxio.demo.elasticsearch.model.AppTranslation elasticsearchAppTranslation = new com.jaxio.demo.elasticsearch.model.AppTranslation();

        elasticsearchAppTranslation.setId(appTranslation.getId());
        elasticsearchAppTranslation.setLanguage(appTranslation.getLanguage());
        elasticsearchAppTranslation.setKey(appTranslation.getKey());
        elasticsearchAppTranslation.setValue(appTranslation.getValue());

        return elasticsearchAppTranslation;
    }
}
