/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/utils/EntityUtils.e.vm.java
 */
package com.jaxio.demo.utils;

import java.math.BigDecimal;

import com.jaxio.demo.jpa.model.Book;

public class BookEntityUtils {

    public static Book createNewBook(String id) {
        Book book = new Book();
        // FIXME à terminer		
        /*		
        		book.setId("Toto");
        		book.setTitle("Toto");
        		book.setDescription("Toto");
        		book.setPublicationDate("Toto");
        		book.setAuthorId("Toto");
        		book.setPrice("Toto");
        		book.setBarcodeid("Toto");
        */
        return book;
    }

    public static com.jaxio.demo.elasticsearch.model.Book createNewElasticsearchBook(String id) {
        com.jaxio.demo.elasticsearch.model.Book book = new com.jaxio.demo.elasticsearch.model.Book();

        return book;
    }

    public static com.jaxio.demo.elasticsearch.model.Book convertToElasticsearchBook(Book book) {
        com.jaxio.demo.elasticsearch.model.Book elasticsearchBook = new com.jaxio.demo.elasticsearch.model.Book();

        elasticsearchBook.setId(book.getId());
        elasticsearchBook.setTitle(book.getTitle());
        elasticsearchBook.setDescription(book.getDescription());
        elasticsearchBook.setPublicationDate(book.getPublicationDate());
        elasticsearchBook.setAuthorId(book.getAuthorId());
        elasticsearchBook.setPrice(book.getPrice());
        elasticsearchBook.setBarcodeid(book.getBarcodeid());

        return elasticsearchBook;
    }
}
