/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/utils/EntityUtils.p.vm.java
 */
package com.jaxio.demo.utils;

import java.math.BigDecimal;

import com.jaxio.demo.jpa.model.Book;

public class EntityUtils {

    public static Book createNewBook(String id) {
        Book book = new Book();
        book.setId(id);
        book.setTitle("Title " + id);
        book.setPrice(new BigDecimal(1));
        book.setDescription("a detailed description !");

        return book;
    }

    public static com.jaxio.demo.elasticsearch.model.Book createNewElasticsearchBook(String id) {
        return new com.jaxio.demo.elasticsearch.model.Book(id, "Titre " + id);
    }

    public static com.jaxio.demo.elasticsearch.model.Book convertToElasticsearchBook(Book book) {
        com.jaxio.demo.elasticsearch.model.Book elasticsearchBook = new com.jaxio.demo.elasticsearch.model.Book();

        elasticsearchBook.setId(book.getId());
        elasticsearchBook.setTitle(book.getTitle());

        return elasticsearchBook;
    }
}
