/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/elasticsearch/model/ElasticsearchEntity.e.vm.java
 */
package com.jaxio.demo.elasticsearch.model;

import org.springframework.data.elasticsearch.annotations.Document;

/**
 * entity AppAuthority for Elasticsearch.
 *
 */
@Document(indexName = "appauthority_index", type = "appAuthorities")
public class AppAuthority {

    private Integer id;
    private String name;

    /**
     * Default constructor.
     */
    public AppAuthority() {
        super();
    }

    public AppAuthority(Integer id, String name) {
        this.id = id;
        this.name = name;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public String toString() {
        return "AppAuthority{" + "id='" + id + '\'' + ", id='" + id + '\'' + ", name='" + name + '\'' + '}';
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((name == null) ? 0 : name.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }

        AppAuthority other = (AppAuthority) obj;

        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        if (name == null) {
            if (other.name != null) {
                return false;
            }
        } else if (!name.equals(other.name)) {
            return false;
        }

        return true;
    }
}
