/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/elasticsearch/model/ElasticsearchEntity.e.vm.java
 */
package com.jaxio.demo.elasticsearch.model;

import org.springframework.data.elasticsearch.annotations.Document;

/**
 * entity AppParameter for Elasticsearch.
 *
 */
@Document(indexName = "appparameter_index", type = "appParameters")
public class AppParameter {

    private Integer id;
    private String domain;
    private String key;
    private String value;

    /**
     * Default constructor.
     */
    public AppParameter() {
        super();
    }

    public AppParameter(Integer id, String domain, String key, String value) {
        this.id = id;
        this.domain = domain;
        this.key = key;
        this.value = value;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public void setValue(String value) {
        this.value = value;
    }

    @Override
    public String toString() {
        return "AppParameter{" + "id='" + id + '\'' + ", id='" + id + '\'' + ", domain='" + domain + '\'' + ", key='" + key + '\'' + ", value='" + value + '\''
                + '}';
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((domain == null) ? 0 : domain.hashCode());
        result = prime * result + ((key == null) ? 0 : key.hashCode());
        result = prime * result + ((value == null) ? 0 : value.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }

        AppParameter other = (AppParameter) obj;

        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        if (domain == null) {
            if (other.domain != null) {
                return false;
            }
        } else if (!domain.equals(other.domain)) {
            return false;
        }
        if (key == null) {
            if (other.key != null) {
                return false;
            }
        } else if (!key.equals(other.key)) {
            return false;
        }
        if (value == null) {
            if (other.value != null) {
                return false;
            }
        } else if (!value.equals(other.value)) {
            return false;
        }

        return true;
    }
}
