/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/elasticsearch/model/ElasticsearchEntity.e.vm.java
 */
package com.jaxio.demo.elasticsearch.model;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.data.elasticsearch.annotations.Document;

/**
 * entity Book for Elasticsearch.
 *
 */
@Document(indexName = "book_index", type = "books")
public class Book {

    private String id;
    private String title;
    private String description;
    private Date publicationDate;
    private Integer authorId;
    private BigDecimal price;
    private Integer barcodeid;

    /**
     * Default constructor.
     */
    public Book() {
        super();
    }

    public Book(String id, String title, String description, Date publicationDate, Integer authorId, BigDecimal price, Integer barcodeid) {
        this.id = id;
        this.title = title;
        this.description = description;
        this.publicationDate = publicationDate;
        this.authorId = authorId;
        this.price = price;
        this.barcodeid = barcodeid;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setPublicationDate(Date publicationDate) {
        this.publicationDate = publicationDate;
    }

    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public void setBarcodeid(Integer barcodeid) {
        this.barcodeid = barcodeid;
    }

    @Override
    public String toString() {
        return "Book{" + "id='" + id + '\'' + ", id='" + id + '\'' + ", title='" + title + '\'' + ", description='" + description + '\'' + ", publicationDate='"
                + publicationDate + '\'' + ", authorId='" + authorId + '\'' + ", price='" + price + '\'' + ", barcodeid='" + barcodeid + '\'' + '}';
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;

        result = prime * result + ((id == null) ? 0 : id.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        result = prime * result + ((description == null) ? 0 : description.hashCode());
        result = prime * result + ((publicationDate == null) ? 0 : publicationDate.hashCode());
        result = prime * result + ((authorId == null) ? 0 : authorId.hashCode());
        result = prime * result + ((price == null) ? 0 : price.hashCode());
        result = prime * result + ((barcodeid == null) ? 0 : barcodeid.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }

        Book other = (Book) obj;

        if (id == null) {
            if (other.id != null) {
                return false;
            }
        } else if (!id.equals(other.id)) {
            return false;
        }
        if (title == null) {
            if (other.title != null) {
                return false;
            }
        } else if (!title.equals(other.title)) {
            return false;
        }
        if (description == null) {
            if (other.description != null) {
                return false;
            }
        } else if (!description.equals(other.description)) {
            return false;
        }
        if (publicationDate == null) {
            if (other.publicationDate != null) {
                return false;
            }
        } else if (!publicationDate.equals(other.publicationDate)) {
            return false;
        }
        if (authorId == null) {
            if (other.authorId != null) {
                return false;
            }
        } else if (!authorId.equals(other.authorId)) {
            return false;
        }
        if (price == null) {
            if (other.price != null) {
                return false;
            }
        } else if (!price.equals(other.price)) {
            return false;
        }
        if (barcodeid == null) {
            if (other.barcodeid != null) {
                return false;
            }
        } else if (!barcodeid.equals(other.barcodeid)) {
            return false;
        }

        return true;
    }
}
