/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/jpa/model/EntityMeta_.e.vm.java
 */
package com.jaxio.demo.jpa.model;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(AppParameter.class)
public abstract class AppParameter_ {

    // Raw attributes
    public static volatile SingularAttribute<AppParameter, Integer> id;
    public static volatile SingularAttribute<AppParameter, String> domain;
    public static volatile SingularAttribute<AppParameter, String> key;
    public static volatile SingularAttribute<AppParameter, String> value;
}