/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/domain/EntityMeta_.e.vm.java
 */
package com.jaxio.demo.jpa.model;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(AppUser.class)
public abstract class AppUser_ {

    // Raw attributes
    public static volatile SingularAttribute<AppUser, Integer> id;
    public static volatile SingularAttribute<AppUser, String> firstName;
    public static volatile SingularAttribute<AppUser, String> lastName;
    public static volatile SingularAttribute<AppUser, String> email;
    public static volatile SingularAttribute<AppUser, String> language;
    public static volatile SingularAttribute<AppUser, String> login;
    public static volatile SingularAttribute<AppUser, String> password;
    public static volatile SingularAttribute<AppUser, Integer> enabled;

    // Many to many
    public static volatile ListAttribute<AppUser, AppAuthority> appAuthorities;
}