/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/jpa/model/EntityMeta_.e.vm.java
 */
package com.jaxio.demo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(AppAuthority.class)
public abstract class AppAuthority_ {

    // Raw attributes
    public static volatile SingularAttribute<AppAuthority, Integer> id;
    public static volatile SingularAttribute<AppAuthority, String> name;
}