/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/jpa/model/EntityMeta_.e.vm.java
 */
package com.jaxio.demo.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(AppTranslation.class)
public abstract class AppTranslation_ {

    // Raw attributes
    public static volatile SingularAttribute<AppTranslation, Integer> id;
    public static volatile SingularAttribute<AppTranslation, String> language;
    public static volatile SingularAttribute<AppTranslation, String> key;
    public static volatile SingularAttribute<AppTranslation, String> value;
}