/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-MyCelerioPack:springboot/src/main/java/domain/Entity.e.vm.java
 */
package com.jaxio.demo.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlTransient;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.jaxio.jpa.querybyexample.Identifiable;

@Entity
@Table(name = "APP_TRANSLATION")

// elastic search index must be lowercase
@org.springframework.data.elasticsearch.annotations.Document(indexName = "apptranslation")
public class AppTranslation implements Identifiable<Integer>, Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger log = Logger.getLogger(AppTranslation.class.getName());

    // Raw attributes
    private Integer id;
    private String language;
    private String key;
    private String value;

    @Override
    public String entityClassName() {
        return AppTranslation.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "ID", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    @Override
    public void setId(Integer id) {
        this.id = id;
    }

    public AppTranslation id(Integer id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    @XmlTransient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [language] ------------------------

    @NotEmpty
    @Size(max = 10)
    @Column(name = "\"LANGUAGE\"", nullable = false, length = 10)
    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public AppTranslation language(String language) {
        setLanguage(language);
        return this;
    }
    // -- [key] ------------------------

    @NotEmpty
    @Size(max = 1000)
    @Column(name = "\"KEY\"", nullable = false, length = 1000)
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public AppTranslation key(String key) {
        setKey(key);
        return this;
    }
    // -- [value] ------------------------

    @Size(max = 4000)
    @Column(name = "\"VALUE\"", length = 4000)
    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public AppTranslation value(String value) {
        setValue(value);
        return this;
    }

    /**
     * Apply the default values.
     */
    public AppTranslation withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof AppTranslation && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this AppTranslation instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("language", getLanguage()) //
                .add("key", getKey()) //
                .add("value", getValue()) //
                .toString();
    }
}