$output.resource("application.properties")##

#elasticsearch.clustername = mkyong-cluster
#elasticsearch.host = localhost
#elasticsearch.port = 9300

#
# Home directory of the embedded Elasticsearch instance. Default to the
# current working directory.
#
spring.data.elasticsearch.properties.path.home=target/elastic
spring.data.elasticsearch.properties.transport.tcp.connect_timeout=120s


spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.show_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true

# root log level
logging.level.root=WARN
# specific log level
logging.level.com.jaxio.demo=INFO